name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please fill out this form as completely as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        What other approaches might solve this problem?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: |
        Screenshots, links to related issues, environment details, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Implementation
      description: Let us know if you plan to help implement this feature
      options:
        - label: I plan to submit a pull request for this feature if accepted
          required: false
